name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Project
      run: |
        git clone https://github.com/google/googletest.git
        mkdir build
        cd build
        cmake ../sim
        make

    - name: Run Tests
      run: |
        cd build
        cd tests
        ./tests
